import Head from 'next/head'
import { Inter } from '@next/font/google'
import { HomePage } from '../src/components/home/home-page'

/**
 * ! Events Index
 * Three different ways to return {title}
 *  1. (props) 2. const {title} = props; 3. props.title
 * 
 * Within main className={styles.main} we are dynamically loading using data.json in the data folder
 *    Meaning we have pages being generated from our database using Data Fetching
 *       Static Generation is the alternative which pregenerate all the pages during build time
 *       (check getStaticPaths on the Next.js documentation)
*/

const inter = Inter({ subsets: ['latin'] })


/**
 * Apply the calling of child class to parent class here
 *   Calling the child class of home-page.jsx from src\components folder
 * 
 */
export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>ICF Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data}/>


    </>
  )
}

/**
 * !Server-Side Function
 * Rendering content on the server side - Must be exported as a stand-alone function never runs on the browser-side
 * and before our home function component 
 */
export async function getServerSideProps() {
  // destructuring data
  const { events_categories } = await import('data/data.json'); // async functions must have await
  // return objects that has props
  return {
      props:{
          data: events_categories
      }
  }
}
